[package]
name = "test_3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
test_1 = { path = "../test_1" }
test_2 = { path = "../test_2" }