[workspace]
members = [
    "test_1",
    "test_2"
]

[workspace.dependencies]
serde = { version = "1.0.164", features = ["derive"] }
serde_yaml = "0.9.21"
quiche = {version = "0.17.2", features=["boringssl-vendored"]}