[package]
name = "test_1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quiche = { workspace = true }

[lib]
name = "test_1"
crate-type = ["cdylib"]